spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 111111jun

mybatis:
    mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    type-aliases-package: com.hujun.mybatisdemo.pojo