server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro_db?useUnicode=true&characterEncoding=utf8
    username: root
    password: 111111jun
mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    type-aliases-package: com.hujun.demo03.pojo

